apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: event-catalog
  namespace: datarecs
spec:
  hosts:
    - events.datarecs.local
  gateways:
    - istio-system/datarecs
  http:
    - route:
        - destination:
            host: event-catalog.datarecs.svc.cluster.local
            port:
              number: 80
